<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <InvariantGlobalization>true</InvariantGlobalization> 
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    </PropertyGroup>
</Project>